server:
  port: 9002 # 注意：这里是9002，不要和9001冲突

spring:
  application:
    name: wzy-order-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}