server:
  port: 8222  # 网关端口

spring:
  application:
    name: wzy-gateway
  zipkin:
    base-url: http://localhost:9041
    sender:
      type: web  # 使用 HTTP 方式发送
    sleuth:
      sampler:
        probability: 1  # 1 表示 100% 采样（生产环境通常调低，实验设为 1 以便必定看到数据）

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Zuul 路由配置
zuul:

  SendErrorFilter:
    error:
      disable: true
  routes:
    # 路由规则1：访问 /client-api/** 转发给 wzy-client-service
    client-route:
      path: /client-api/**
      serviceId: wzy-client-service

    # 路由规则2：访问 /order-api/** 转发给 wzy-order-web
    order-route:
      path: /order-api/**
      serviceId: wzy-order-web