server:
  port: 12000 # 实验要求端口

spring:
  application:
    name: wzy-config-server
  cloud:
    config:
      server:
        # git:
          # 【重要】改成你第一步创建的仓库地址，例如 https://gitee.com/你的用户名/springcloud-config-repo.git
          # uri: https://github.com/Allen-keating/springcloud-config-repo.git
          # default-label: main
          # 如果仓库是私有的，需要配置 username 和 password
          # username: your-username
          # password: your-password
          svn:
            # 填你第一步复制的 SVN URL，注意要包含 trunk
            uri: https://AllenWang/svn/springcloud/trunk
            # SVN 的账号密码
            username: wzy
            password: 123456
            # 默认标签（对应 SVN 的目录结构，通常是 trunk）
            default-label: trunk
  rabbitmq:
    # 请配置你的 RabbitMQ 地址，如果是本机默认安装可不改，容器化部署请改为 IP
    host: localhost
    port: 5672
    username: guest
    password: guest

# 暴露 Actuator 端点
management:
  endpoints:
    web:
      exposure:
        # 开启 bus-refresh 端点，这是触发全自动刷新的开关
        include: bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/